name: FraudDetection
channels:
  - defaults
dependencies:
  - numpy
  - pylint
  - python=3
  - pandas
  - flask
  - scikit-learn
  - pip:
    - pyod
    - plotly
    - seaborn
    - suod
